# Batch mode macro for muon simulation (no visualization)
# Use with: ./exmuons batch.mac
#
# Minimal verbosity for batch processing
/control/verbose 1
/run/verbose 1
#
 
# Run 1: Scintillator 1 at baseline (no offset)
/detector/scint1YOffset 0 cm
/run/reinitializeGeometry
/gps/particle mu-
/run/beamOn 4000000

/gps/particle mu+
/run/beamOn 4000000


# Run 3: Scintillator 1 displaced by 30 cm along Y
/detector/scint1YOffset 47.5 cm
/run/reinitializeGeometry
/gps/particle mu-
/run/beamOn 4000000

/gps/particle mu+
/run/beamOn 4000000

# Run 3: Scintillator 1 displaced by 30 cm along Y
/detector/scint1YOffset 62.5 cm
/run/reinitializeGeometry
/gps/particle mu-
/run/beamOn 4000000

/gps/particle mu+
/run/beamOn 4000000